# This workflows runs when
# 1. pull_request raised to trunk branch.
# 2. tag created on at_tools repository
name: at_tools

on:
  push:
    tags:
      - v**
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies in at_commons
        working-directory: at_commons
        run: dart pub get

      - name: Analyze project source in at_commons
        working-directory: at_commons
        run: dart analyze

      - name: Run tests in at_commons
        working-directory: at_commons
        run: dart test --concurrency=1

      # Actions running in at_utils
      - name: Install dependencies in at_utils
        working-directory: at_utils
        run: dart pub get

      - name: Analyze project source in at_utils
        working-directory: at_utils
        run: dart analyze

      - name: Run tests in at_utils
        working-directory: at_utils
        run: dart test --concurrency=1